apiVersion: v1
kind: Service
metadata:
  name: game-api-service
spec:
  type: LoadBalancer
  selector:
    app: game-api
  ports:
    - port: "80"
      targetPort: "80"
      name: http
    - port: "443"
      targetPort: "443"
      name: https