apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-api
  namespace: default
  labels:
    app: game-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-api
  template:
    metadata:
      labels:
        app: game-api
    spec:
      containers:
        - name: game-api
          image: GameApi20240120144812.azurecr.io/gameapi:latest
          # resources:
          #   limits:
          #     cpu: 50m
          #   requests:
          #     cpu: 20mx
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   runAsNonRoot: false
          #   capabilities:
          #     drop:
          #       - ALL
          #   readOnlyRootFilesystem: true
          ports:
            - containerPort: 80
            - containerPort: 443